### ISSUE TITLE
Fresh clone of master doesn't build due to dependency issue.

### ISSUE THREAD

**Issue by seanparsons** [gemserk/animation4j#3]
Has a dependency on com.gemserk.componentsengine:core:0.0.10-SNAPSHOT that doesn't have a relevant repo available.

[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Components Engine module of animation4j 0.0.14-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.gemserk.componentsengine:core:jar:0.0.10-SNAPSHOT is m
issing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Parent module for Animations 4 Java ............... SUCCESS [49.551s]
[INFO] Core module of Animations project ................. SUCCESS [41.246s]
[INFO] Components Engine module of animation4j ........... FAILURE [0.016s]
[INFO] Java2d module for animation4j ..................... SKIPPED
[INFO] Examples module of animation4j .................... SKIPPED
[INFO] Slick2D module for animation4j .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:30.969s
[INFO] Finished at: Sun Sep 25 19:33:41 BST 2011
[INFO] Final Memory: 18M/120M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project animation4j-componentsengine: Could no
t resolve dependencies for project com.gemserk.animation4j:animation4j-component
sengine:jar:0.0.14-SNAPSHOT: Could not find artifact com.gemserk.componentsengin
e:core:jar:0.0.10-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :animation4j-componentsengine

**Comment by acoppes** [comment]
If you want to use animation4j in your project I recommend you to use it from maven central or just download the jars from the downloads section.

If you want to clone the project to see or modify stuff I recommend you to remove or disable componentsengine and slick2d modules because both require dependencies that are not uploaded to maven central.

I will remove both modules for the next release maybe to avoid this kind of problems based on the fact that both modules contains classes almost not used.

**Comment by acoppes** [comment]
Sean, could you try the removingdeps branch? I was removing some dependencies, copying code and updating some other dependencies version to use stuff deployed on central to avoid problems and let ppl build from a fresh clone.

In resume: animation4j-componentsengine module was removed and animation4j-slick was disabled from the build because the missing dependencies from maven central.

I tested it and it seems to work fine now but tell me if it works for you.
